# Generated by Django 4.1.7 on 2023-02-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_student_pass_matric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
